from .constants import event_metrics as event_metrics, match_metrics as match_metrics, team_event_metrics as team_event_metrics, team_match_metrics as team_match_metrics, team_metrics as team_metrics, team_year_metrics as team_year_metrics, year_metrics as year_metrics
from .validate import check_type as check_type, get_locations as get_locations, get_type as get_type
from _typeshed import Incomplete
from typing import Any

class Statbotics:
    BASE_URL: str
    session: Incomplete
    def __init__(self) -> None: ...
    def get_team(self, team: int, fields: list[str] = ['all']) -> dict[str, Any]: ...
    def get_teams(self, country: str | None = None, state: str | None = None, district: str | None = None, active: bool | None = True, metric: str = 'team', ascending: bool | None = None, limit: int = 100, offset: int = 0, fields: list[str] = ['all']) -> list[dict[str, Any]]: ...
    def get_year(self, year: int, fields: list[str] = ['all']) -> dict[str, Any]: ...
    def get_years(self, metric: str = 'year', ascending: bool | None = None, limit: int = 100, offset: int = 0, fields: list[str] = ['all']) -> list[dict[str, Any]]: ...
    def get_team_year(self, team: int, year: int, fields: list[str] = ['all']) -> dict[str, Any]: ...
    def get_team_years(self, team: int | None = None, year: int | None = None, country: str | None = None, state: str | None = None, district: str | None = None, metric: str = 'team', ascending: bool | None = None, limit: int = 100, offset: int = 0, fields: list[str] = ['all']) -> list[dict[str, Any]]: ...
    def get_event(self, event: str, fields: list[str] = ['all']) -> dict[str, Any]: ...
    def get_events(self, year: int | None = None, country: str | None = None, state: str | None = None, district: str | None = None, type: int | str | None = None, week: int | None = None, metric: str = 'year', ascending: bool | None = None, limit: int = 100, offset: int = 0, fields: list[str] = ['all']) -> list[dict[str, Any]]: ...
    def get_team_event(self, team: int, event: str, fields: list[str] = ['all']) -> dict[str, Any]: ...
    def get_team_events(self, team: int | None = None, year: int | None = None, event: str | None = None, country: str | None = None, state: str | None = None, district: str | None = None, type: int | str | None = None, week: int | None = None, metric: str = 'year', ascending: bool | None = None, limit: int = 0, offset: int = 0, fields: list[str] = ['all']) -> list[dict[str, Any]]: ...
    def get_match(self, match: str, fields: list[str] = ['all']) -> dict[str, Any]: ...
    def get_matches(self, team: int | None = None, year: int | None = None, event: str | None = None, week: int | None = None, elims: bool | None = None, metric: str = 'time', ascending: bool | None = None, limit: int = 200, offset: int = 0, fields: list[str] = ['all']) -> list[dict[str, Any]]: ...
    def get_team_match(self, team: int, match: str, fields: list[str] = ['all']) -> dict[str, Any]: ...
    def get_team_matches(self, team: int | None = None, year: int | None = None, event: str | None = None, match: str | None = None, week: int | None = None, elims: bool | None = None, metric: str = 'time', ascending: bool | None = None, limit: int = 100, offset: int = 0, fields: list[str] = ['all']) -> list[dict[str, Any]]: ...
