from .constants import Canada as Canada, USA as USA, countries as countries, districts as districts
from typing import Any, List, Optional


def check_type(val: int | str |
               Optional[List[Any]], type: str, name: str) -> None: ...


def get_country(country: str) -> str: ...
def get_state(country: Optional[str], state: str) -> tuple[str, str]: ...
def get_district(district: str) -> str: ...
def get_locations(country: Optional[str], state: str |
                  None, district: Optional[str]) -> str: ...


def get_type(type: int | Optional[str]) -> Optional[int]: ...
