from .constants import Canada as Canada, USA as USA, countries as countries, districts as districts
from typing import Any

def check_type(val: int | str | list[Any] | None, type: str, name: str) -> None: ...
def get_country(country: str) -> str: ...
def get_state(country: str | None, state: str) -> tuple[str, str]: ...
def get_district(district: str) -> str: ...
def get_locations(country: str | None, state: str | None, district: str | None) -> str: ...
def get_type(type: int | str | None) -> int | None: ...
