name = "scoutferno"
main = "wrangler.js"
compatibility_date = "2026-03-24"
preview_urls = true

[assets]
directory = "./dist"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false